[default]
src = 'src'
out = 'out'
libs = ['lib']
solc = "0.8.10" # to use a specific local solc install set the path as `solc = "<path to solc>/solc"`
cache = true
cache_path = 'cache'
optimization = true
optimizer_runs = 2000
etherscan_api_key="YOURETHERSCANAPIKEY"
remappings = ["ds-test/=lib/ds-test/src/", "@openzeppelin/=lib/openzeppelin-contracts/"]

[default.rpc_endpoints]
mainnet = "https://eth-mainnet.g.alchemy.com/v2/FOUNDRY_ALCHEMY_API_KEY"
optimism = "https://optimism.alchemyapi.io/v2/FOUNDRY_ALCHEMY_API_KEY"

# See more config options https://github.com/gakonst/foundry/tree/master/config
